# Generated by Django 3.2.4 on 2021-06-22 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='categoria_libro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_categoria', models.CharField(max_length=50)),
                ('nombre_categoria', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='libro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_libro', models.CharField(max_length=50)),
                ('nombre_libro', models.CharField(max_length=50)),
                ('autor_libro', models.CharField(max_length=50)),
                ('descripcion_libro', models.CharField(max_length=50)),
            ],
        ),
    ]
