# Generated by Django 3.2.4 on 2021-06-22 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoria_libro',
            name='id_categoria',
        ),
        migrations.RemoveField(
            model_name='libro',
            name='id_libro',
        ),
    ]
