# Generated by Django 3.2.5 on 2021-07-25 18:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20210725_1503'),
    ]

    operations = [
        migrations.AddField(
            model_name='libro',
            name='Banco',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.banco'),
            preserve_default=False,
        ),
    ]
