# Generated by Django 3.2.5 on 2021-07-25 18:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_libro_banco'),
    ]

    operations = [
        migrations.AddField(
            model_name='banco',
            name='Pais',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.pais'),
            preserve_default=False,
        ),
    ]
