# Generated by Django 3.2.5 on 2021-07-25 18:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_banco_pais'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='libro',
            name='Banco',
        ),
        migrations.AddField(
            model_name='libro',
            name='Pais',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.pais'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='libro',
            name='autor_libro',
            field=models.CharField(max_length=50, verbose_name='Autor del libro'),
        ),
        migrations.AlterField(
            model_name='libro',
            name='descripcion_libro',
            field=models.CharField(max_length=50, verbose_name='Descripcion del libro'),
        ),
        migrations.AlterField(
            model_name='libro',
            name='id_libro',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='Identificador del libro'),
        ),
        migrations.AlterField(
            model_name='libro',
            name='nombre_libro',
            field=models.CharField(max_length=50, verbose_name='Nombre del libro'),
        ),
    ]
