# Generated by Django 3.2.5 on 2021-07-25 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20210725_1841'),
    ]

    operations = [
        migrations.AddField(
            model_name='banco',
            name='horario1',
            field=models.BooleanField(default=False),
        ),
    ]
