# Generated by Django 3.2.5 on 2021-07-25 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_banco_horario1'),
    ]

    operations = [
        migrations.AddField(
            model_name='banco',
            name='horario2',
            field=models.BooleanField(default=False, verbose_name='De 02:00 a 04:00'),
        ),
        migrations.AlterField(
            model_name='banco',
            name='horario1',
            field=models.BooleanField(default=False, verbose_name='De 00:00 a 02:00'),
        ),
    ]
