# Generated by Django 3.2.5 on 2021-07-26 03:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20210725_2003'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='libro',
            name='Pais',
        ),
    ]
