# Generated by Django 3.2.5 on 2021-07-26 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_remove_libro_pais'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='libro',
            name='id_libro',
        ),
        migrations.AddField(
            model_name='libro',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
