# Generated by Django 3.2.5 on 2021-07-26 04:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20210726_0424'),
    ]

    operations = [
        migrations.RenameField(
            model_name='libro',
            old_name='Categoria_libro',
            new_name='categoria_libro',
        ),
    ]
